### ISSUE TITLE
target:win2012 r2 

### ISSUE THREAD

**Issue by hongwei520** [WazeHell/sam-the-admin#1]
It looks like it succeeded. What's the reason?

![1639450981(1)](https://user-images.githubusercontent.com/39451921/145925629-9b56c43e-5ebd-40c5-a63c-9b45e9a16cab.jpg)

**Comment by mtkilicc** [comment]
I had issue like that. In my case, selected target and the IP which in argument are different. For example I attack to DC is dc01.example.local and the DC IP is 10.0.0.1. I used that IP for attack but when executing script, selected target value is dc02.example.local. After that I change the IP 10.0.0.2 that related other DC(dc02...) and the attack have been succesfull. Maybe you have same problem. Just look at selected target and the IP are same or not.

**Comment by TradeTechnology** [comment]
> I had issue like that. In my case, selected target and the IP which in argument are different. For example I attack to DC is dc01.example.local and the DC IP is 10.0.0.1. I used that IP for attack but when executing script, selected target value is dc02.example.local. After that I change the IP 10.0.0.2 that related other DC(dc02...) and the attack have been succesfull. Maybe you have same problem. Just look at selected target and the IP are same or not.


Help me please....

My ip is: 10.0.1.1
Name Server: SRVWIN001XXDC01
Comand: sudo python3 sam_the_admin.py "test.local/pentest:@Password1" -dc-ip 10.0.1.1 -shell  

Execute:


Execute:
[*] Selected Target srvwin032xxdc01.test.local

Why does it select a wrong Target if I'm putting the matching IP?

Real name server: SRVWIN001XXDC01
Target: srvwin032xxdc01

Help me?

**Comment by Zepahana** [comment]
rc host is a mother of a female merged with a persayfather the host 2 is implying that a mother will take a child place like its supposed to because its dc the child is no more so a child female merged would be a sister component with the tree I was able to merge Jackie with Jack and evolve into what body I had of today remembering also that Christian byway I am Jackie's sister when my mother was my sistister child's fatherd my mothers grandchildren family of LaChapelle granddaughter is I slegh  grandfathers mother sleghdom ciro to Damascus who is my wife granddaughters husband base my song for his sisters daughter hers parents were anyichristes....

Orrrrr my father has dementia .
